# -- coding:utf-8 --
# A simple example using the HTTP plugin that shows the retrieval of a
# single page via HTTP.
#
# This script is automatically generated by ngrinder.
#
# @author dongsikchoi.dev
from net.grinder.script.Grinder import grinder
from net.grinder.script import Test
from net.grinder.plugin.http import HTTPRequest
from net.grinder.plugin.http import HTTPPluginControl
from java.util import Date
import httplib
import urllib
from HTTPClient import NVPair, Cookie, CookieModule


control = HTTPPluginControl.getConnectionDefaults()


# if you don't want that HTTPRequest follows the redirection, please modify the following option 0.
# control.followRedirects = 1
# if you want to increase the timeout, please modify the following option.
control.timeout = 6000
test1 = Test(1, "example.com")

# Set header data if you need 
#headers = [] # Array of NVPair
#headers.append(NVPair("Content-Type", "application/json"),)

cookies = [] # Array of Cookie
class TestRunner:
	# initlialize a thread
	def __init__(self):
		test1.record(TestRunner.__call__)
		grinder.statistics.delayReports=True
		pass
	
	def before(self):
        # Add headers if needed as mentioned in line 28
		#request1.headers = headers 
		for c in cookies: CookieModule.addCookie(c, HTTPPluginControl.getThreadHTTPClientContext())


	def __call__(self):
		self.before()
		
		params = urllib.urlencode({'id': 'johndoe', 'pw': 'password_sample',})
		data = params
		headers = {'Content-type': 'application/x-www-form-urlencoded', 'Accept': 'text/plain'}
		url = '/login'
		conn = httplib.HTTPSConnection('example.com')
		conn.request('POST',url,data,headers)
		response = conn.getresponse()
		print('response status = ',response.status)
		print('response result', response.read())
		conn.close()
		